[package]
name = "incantata"
version = "0.1.0"
edition = "2021"

[lib]
name = "incantata"
path = "src/lib.rs"

[[bin]]
name = "incantata"
path = "src/main.rs"

[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
rand = "0.8.4"
